### ISSUE TITLE
按readme配置了没有出现info: CookieCloud loaded，也没有cookiecloud的路由

### ISSUE THREAD

**Issue by saaak** [sgpublic/rsshub-cookiecloud#3]
这是我的docker compose文件
```yaml
services:
    rsshub:
        image: diygod/rsshub
        restart: always
        ports:
          - "1200:1200"
          - "4651:4651"
        environment:
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: "redis://redis:6379/"
            PUPPETEER_WS_ENDPOINT: "ws://browserless:3000" # marked
            COOKIE_CLOUD_HOST: 'http://cookiecloud:8088'
            COOKIE_CLOUD_UUID: ''
            COOKIE_CLOUD_PASSWORD: ''
            COOKIE_CLOUD_INTERVAL: 3600
        volumes:
          - ./cookiecloud/cookiecloud:/app/lib/api/cookiecloud
        command: ["npm", "run", "dev"]
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:1200/healthz"]
            interval: 30s
            timeout: 10s
            retries: 3
        depends_on:
            - redis
            - browserless # marked
            - cookiecloud

    browserless: # marked
        image: browserless/chrome # marked
        restart: always # marked
        ulimits: # marked
            core: # marked
                hard: 0 # marked
                soft: 0 # marked
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000/pressure"]
            interval: 30s
            timeout: 10s
            retries: 3

    redis:
        image: redis:alpine
        restart: always
        volumes:
            - ./redis-data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 5s
    
    cookiecloud:
        image: easychen/cookiecloud
        user: 1000:1001
        volumes:
          - ./data:/data/api/data
        ports:
          - "8088:8088"
        restart: always
```
