### ISSUE TITLE
load成功了但好像抓去失败了

### ISSUE THREAD

**Issue by zsszyx** [sgpublic/rsshub-cookiecloud#6]
<img width="713" alt="Image" src="https://github.com/user-attachments/assets/880884b5-7b0f-46d5-92ee-ae89efcb276d" />

**Comment by sgpublic** [comment]
请检查 cookiecloud 相关配置是否正确。

**Comment by zsszyx** [comment]
```
services:
    rsshub:
        # two ways to enable puppeteer:
        # * comment out marked lines, then use this image instead: diygod/rsshub:chromium-bundled
        # * (consumes more disk space and memory) leave everything unchanged
        image: diygod/rsshub
        restart: always
        ports:
            - "1200:1200"
        environment:
            CACHE_TYPE: redis
            REDIS_URL: "redis://redis:6379/"
            PUPPETEER_WS_ENDPOINT: "ws://browserless:3000" # marked

            COOKIE_CLOUD_HOST: 'http://localhost:8088'
            COOKIE_CLOUD_UUID: 'rsshub'
            COOKIE_CLOUD_PASSWORD: 'rsshub-pwd'
            COOKIE_CLOUD_INTERVAL: 3600
            COOKIE_CLOUD_DEBUG: true
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:1200/healthz"]
            interval: 30s
            timeout: 10s
            retries: 3
        depends_on:
            - redis
            - browserless # marked
        env_file: stack.env
        volumes:
            - ./cookiecloud:/app/lib/routes/cookiecloud
        command: ["npm", "run", "dev"]

    browserless: # marked
        image: browserless/chrome # marked
        restart: always # marked
        ulimits: # marked
            core: # marked
                hard: 0 # marked
                soft: 0 # marked
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000/pressure"]
            interval: 30s
            timeout: 10s
            retries: 3

    redis:
        image: redis:alpine
        restart: always
        volumes:
            - redis-data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 5s
    
    cookiecloud:
        image: easychen/cookiecloud:2023.01.20.16.39
        ports:
            - 8088:8088
        user: 1000:1001
        volumes:
        - ./data:/data/api/data
        restart: always

volumes:
    redis-data:
```
是不是因为不能用无头浏览器呢？
